<a href="https://colab.research.google.com/github/skaran786/Wipro-s-Sustainability-Machine-Learning-Challenge/blob/main/WiproComp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb
#!ls  # Check if required cuda 9.0 amd64-deb file is downloaded
#!dpkg -i cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb
#!ls /var/cuda-repo-9-0-local | grep .pub
#!apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub
#!apt-get update
#!sudo apt-get install cuda-9.0

--2022-01-27 12:48:57--  https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb
Resolving developer.nvidia.com (developer.nvidia.com)... 152.195.19.142
Connecting to developer.nvidia.com (developer.nvidia.com)|152.195.19.142|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://developer.nvidia.com/compute/cuda/9.0/prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb [following]
--2022-01-27 12:48:58--  https://developer.nvidia.com/compute/cuda/9.0/prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb
Reusing existing connection to developer.nvidia.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/9.0/secure/Prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64.deb?ugIiUboWlO15LIIZ9O54kZL4yFJ5_egZduubHAgtNrdKFWhVJXDJ9EIqvKXUNSVAkz37OLrm9bNWEepStaA-wYdjf7DZ9

In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


In [ ]:
!pip install thundersvm

     |████████████████████████████████| 507 kB 12.2 MB/s 


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [2]:
def scaling(df):
    '''This function will scale the data using Standard Scaler'''
    scale = StandardScaler()
    col = df.columns
    df = pd.DataFrame(scale.fit_transform(df))
    df.columns = col
    return df

In [3]:
df = pd.read_csv('/content/drive/MyDrive/WiproCompetetion/train.csv')
df.head()

Year  Month  Day  ...  Wind Direction  Wind Speed  Fill Flag
0  2009      1    1  ...           346.1         3.1          0
1  2009      1    1  ...           346.1         3.1          0
2  2009      1    1  ...           347.9         3.2          0
3  2009      1    1  ...           347.9         3.1          0
4  2009      1    1  ...           350.0         3.0          0

[5 rows x 18 columns]

In [4]:
df.isnull().sum()

Year                  0
Month                 0
Day                   0
Hour                  0
Minute                0
Clearsky DHI          0
Clearsky DNI          0
Clearsky GHI          0
Cloud Type            0
Dew Point             0
Temperature           0
Pressure              0
Relative Humidity     0
Solar Zenith Angle    0
Precipitable Water    0
Wind Direction        0
Wind Speed            0
Fill Flag             0
dtype: int64

In [5]:
df.describe()

Year          Month  ...     Wind Speed      Fill Flag
count  175296.000000  175296.000000  ...  175296.000000  175296.000000
mean     2013.500274       6.523549  ...       2.262871       0.740433
std         2.871908       3.448543  ...       1.281902       6.575655
min      2009.000000       1.000000  ...       0.000000       0.000000
25%      2011.000000       4.000000  ...       1.300000       0.000000
50%      2013.500000       7.000000  ...       2.000000       0.000000
75%      2016.000000      10.000000  ...       3.000000       0.000000
max      2018.000000      12.000000  ...      12.900000     100.000000

[8 rows x 18 columns]

In [6]:
y1 = df[['Clearsky DHI','Clearsky DNI','Clearsky GHI']]
X_train = df.drop(['Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI'], axis=1)

#y2 = df['Clearsky DNI']
#y3 = df['Clearsky GHI']

In [7]:
X_train = scaling(X_train)

In [10]:
print(y1.head())

   Clearsky DHI  Clearsky DNI  Clearsky GHI
0             0             0             0
1             0             0             0
2             0             0             0
3             0             0             0
4             0             0             0


In [11]:
gbr1 = GradientBoostingRegressor()
model1 = MultiOutputRegressor(estimator=gbr1)
print(model1)
gbr2 = GradientBoostingRegressor()
model2 = MultiOutputRegressor(estimator=gbr2)
print(model2)
gbr3 = GradientBoostingRegressor()
model3 = MultiOutputRegressor(estimator=gbr3)
print(model3)

MultiOutputRegressor(estimator=GradientBoostingRegressor())
MultiOutputRegressor(estimator=GradientBoostingRegressor())
MultiOutputRegressor(estimator=GradientBoostingRegressor())


In [12]:
print("Training model")
print("Model 1 started")
model1.fit(X_train,y1)
print("Model 1 ended")
#print("Model 2 started")
#model2.fit(X_train,y2)
#print("Model 2 ended")
#print("Model 3 started")
#model3.fit(X_train,y3)
#print("Model 3 ended")
#print("Training done..")

Training model
Model 1 started
Model 1 ended


In [13]:
score = model1.score(X_train, y1)
print("Training score:", score)

Training score: 0.9767838092805933


In [ ]:
import pickle

filename1 = '/content/drive/MyDrive/WiproCompetetion/finalized_model1.sav'
filename2 = '/content/drive/MyDrive/WiproCompetetion/finalized_model2.sav'
filename3 = '/content/drive/MyDrive/WiproCompetetion/finalized_model3.sav'
pickle.dump(model1, open(filename1, 'wb'))
#pickle.dump(model1, open(filename2, 'wb'))
#pickle.dump(model1, open(filename3, 'wb'))

In [ ]:
loaded_model = pickle.load(open(filename1, 'rb'))
result = loaded_model.score(X_train,y1)
print(result)

0.976783809280593


In [18]:
test = pd.read_csv('/content/drive/MyDrive/WiproCompetetion//test.csv')
test.head()

Year  Month  Day  Hour  ...  Fill Flag  Clearsky DHI  Clearsky DNI  Clearsky GHI
0  2019      1    1     0  ...          0           NaN           NaN           NaN
1  2019      1    1     0  ...          0           NaN           NaN           NaN
2  2019      1    1     1  ...          0           NaN           NaN           NaN
3  2019      1    1     1  ...          0           NaN           NaN           NaN
4  2019      1    1     2  ...          0           NaN           NaN           NaN

[5 rows x 18 columns]

In [19]:
X_test = test.drop(['Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI'], axis=1)
xpred=test[['Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI']]
X_test = scaling(X_test)

In [21]:
ypred = model1.predict(X_train)
print(ypred)
ypred1=model1.predict(X_test)

[[-2.27670195e-01  3.13392319e+00  1.55148851e-01]
 [-2.27670195e-01  1.79217528e+00  4.47323761e-01]
 [ 1.36421343e-01  2.96618503e+00  5.76765387e-02]
 ...
 [ 1.30986272e+01  1.06145986e+02  1.88420172e+01]
 [ 2.50321252e-01  5.19509206e+00  3.07316833e-01]
 [ 2.50321252e-01  1.42211195e+00  7.66656693e-02]]


In [22]:
test[['Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI']] = ypred1

In [23]:
print("y1 MSE:%.4f" % mean_squared_error(y1, ypred))

y1 MSE:603.5752


In [ ]:
import pickle
loaded_model = pickle.load(open('finalized_model1.sav', 'rb'))
result1 = loaded_model.score(X_test,y1)

In [ ]:
pred1 = model1.predict(X_test).astype('int32')
pred2 = model2.predict(X_test).astype('int32')
pred3 = model3.predict(X_test).astype('int32')

In [ ]:
test['Clearsky DHI'] = pred1
test['Clearsky DNI'] = pred2
test['Clearsky GHI'] = pred3

In [24]:
submission = test[['Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI']]
submission.to_csv('submission.csv', index=False)

In [9]:
import tensorflow as tf

In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, kernel_initializer='normal', activation='relu'),
    tf.keras.layers.Dense(256, kernel_initializer='normal',activation='relu'),
    tf.keras.layers.Dense(256, kernel_initializer='normal',activation='relu'),
    tf.keras.layers.Dense(256, kernel_initializer='normal',activation='relu'),
    tf.keras.layers.Dense(384, kernel_initializer='normal',activation='relu'),
    tf.keras.layers.Dense(384, kernel_initializer='normal',activation='relu'),
    tf.keras.layers.Dense(1, kernel_initializer='normal',activation='linear')
])

loss_fn = tf.keras.losses.MeanSquaredLogarithmicError()
model.compile(loss= loss_fn, optimizer='adam', metrics=[loss_fn])
model.fit(X_train, y1, epochs=15, batch_size=64, validation_split = 0.2, verbose =0)


In [20]:
ykeras=model.predict(X_train)

In [22]:
ykeras.view

<function ndarray.view>

In [17]:
print("y1 MSE:%.4f" % mean_squared_error(y1, ykeras))

ValueError: ignored